import type { CategoryIconKey } from '@spendly/shared'
import {
  Apple,
  AppWindow,
  Baby,
  Banknote,
  Beer,
  Bike,
  BookOpen,
  Bone,
  Briefcase,
  Building2,
  BusFront,
  Car,
  CirclePlus,
  Clapperboard,
  Coffee,
  CreditCard,
  Croissant,
  Droplet,
  Dumbbell,
  Ellipsis,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HandCoins,
  HeartPulse,
  House,
  KeyRound,
  Landmark,
  Laptop,
  Music,
  PartyPopper,
  PawPrint,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Receipt,
  Repeat,
  Scissors,
  ShieldPlus,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  SquareParking,
  Stethoscope,
  Ticket,
  TrendingUp,
  Tv,
  Undo2,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/**
 * Icon key (stored in the database) → icon component. Typed as a complete Record, so
 * adding a key to @spendly/shared without an icon here fails the build.
 */
export const CATEGORY_ICONS: Record<CategoryIconKey, LucideIcon> = {
  wallet: Wallet,
  'piggy-bank': PiggyBank,
  banknote: Banknote,
  'credit-card': CreditCard,
  'hand-coins': HandCoins,
  briefcase: Briefcase,
  laptop: Laptop,
  'trending-up': TrendingUp,
  undo: Undo2,
  gift: Gift,
  'circle-plus': CirclePlus,
  ellipsis: Ellipsis,
  receipt: Receipt,
  landmark: Landmark,
  'shopping-cart': ShoppingCart,
  apple: Apple,
  croissant: Croissant,
  utensils: Utensils,
  pizza: Pizza,
  coffee: Coffee,
  beer: Beer,
  house: House,
  key: KeyRound,
  building: Building2,
  zap: Zap,
  droplet: Droplet,
  wifi: Wifi,
  flame: Flame,
  wrench: Wrench,
  sofa: Sofa,
  car: Car,
  fuel: Fuel,
  bus: BusFront,
  parking: SquareParking,
  bike: Bike,
  plane: Plane,
  'heart-pulse': HeartPulse,
  pill: Pill,
  stethoscope: Stethoscope,
  'shield-plus': ShieldPlus,
  dumbbell: Dumbbell,
  sparkles: Sparkles,
  scissors: Scissors,
  'party-popper': PartyPopper,
  clapperboard: Clapperboard,
  ticket: Ticket,
  gamepad: Gamepad2,
  music: Music,
  tv: Tv,
  repeat: Repeat,
  'app-window': AppWindow,
  'shopping-bag': ShoppingBag,
  shirt: Shirt,
  smartphone: Smartphone,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  'paw-print': PawPrint,
  bone: Bone,
  baby: Baby,
}
