/**
 * Icon keys a category can use. The database stores the key; the web app maps each key
 * to an icon component (see apps/web/src/components/category/category-icons.ts), and
 * TypeScript fails the build if a key is missing there.
 */
export const CATEGORY_ICON_KEYS = [
  // money & generic
  'wallet',
  'piggy-bank',
  'banknote',
  'credit-card',
  'hand-coins',
  'briefcase',
  'laptop',
  'trending-up',
  'undo',
  'gift',
  'circle-plus',
  'ellipsis',
  'receipt',
  'landmark',
  // food
  'shopping-cart',
  'apple',
  'croissant',
  'utensils',
  'pizza',
  'coffee',
  'beer',
  // home
  'house',
  'key',
  'building',
  'zap',
  'droplet',
  'wifi',
  'flame',
  'wrench',
  'sofa',
  // transport
  'car',
  'fuel',
  'bus',
  'parking',
  'bike',
  'plane',
  // health & care
  'heart-pulse',
  'pill',
  'stethoscope',
  'shield-plus',
  'dumbbell',
  'sparkles',
  'scissors',
  // leisure & subscriptions
  'party-popper',
  'clapperboard',
  'ticket',
  'gamepad',
  'music',
  'tv',
  'repeat',
  'app-window',
  // shopping & education
  'shopping-bag',
  'shirt',
  'smartphone',
  'graduation-cap',
  'book-open',
  // family & pets
  'paw-print',
  'bone',
  'baby',
] as const

export type CategoryIconKey = (typeof CATEGORY_ICON_KEYS)[number]

export function isCategoryIconKey(value: string): value is CategoryIconKey {
  return (CATEGORY_ICON_KEYS as readonly string[]).includes(value)
}

/** pt-BR names, for screen readers and tooltips in the icon picker. */
export const CATEGORY_ICON_LABELS: Record<CategoryIconKey, string> = {
  wallet: 'Carteira',
  'piggy-bank': 'Cofrinho',
  banknote: 'Dinheiro',
  'credit-card': 'Cartão',
  'hand-coins': 'Moedas na mão',
  briefcase: 'Maleta',
  laptop: 'Notebook',
  'trending-up': 'Gráfico subindo',
  undo: 'Devolução',
  gift: 'Presente',
  'circle-plus': 'Mais',
  ellipsis: 'Outros',
  receipt: 'Recibo',
  landmark: 'Banco',
  'shopping-cart': 'Carrinho',
  apple: 'Maçã',
  croissant: 'Croissant',
  utensils: 'Talheres',
  pizza: 'Pizza',
  coffee: 'Café',
  beer: 'Cerveja',
  house: 'Casa',
  key: 'Chave',
  building: 'Prédio',
  zap: 'Energia',
  droplet: 'Água',
  wifi: 'Wi-Fi',
  flame: 'Fogo',
  wrench: 'Ferramenta',
  sofa: 'Sofá',
  car: 'Carro',
  fuel: 'Combustível',
  bus: 'Ônibus',
  parking: 'Estacionamento',
  bike: 'Bicicleta',
  plane: 'Avião',
  'heart-pulse': 'Saúde',
  pill: 'Remédio',
  stethoscope: 'Estetoscópio',
  'shield-plus': 'Proteção',
  dumbbell: 'Academia',
  sparkles: 'Brilho',
  scissors: 'Tesoura',
  'party-popper': 'Festa',
  clapperboard: 'Cinema',
  ticket: 'Ingresso',
  gamepad: 'Videogame',
  music: 'Música',
  tv: 'TV',
  repeat: 'Assinatura',
  'app-window': 'Aplicativo',
  'shopping-bag': 'Sacola',
  shirt: 'Roupa',
  smartphone: 'Celular',
  'graduation-cap': 'Formatura',
  'book-open': 'Livro',
  'paw-print': 'Pata',
  bone: 'Osso',
  baby: 'Bebê',
}
